# Site settings

title: LDSoftware
email: info@ldsoftware.it
description: >- 
  Italian developer, at first just for passion, then as a full time job.
  Big enthusiast of functional programming and all the things that make code readable,
  maintainable and mathematically correct.
baseurl: ""
url: "https://ldsoftware.it"
twitter_username: LucaMacGyver
github_username:  LukeDS-it
linkedin_username: luca-di-stefano-31224b3b
last_update: Tue, 23 June 2020
permalink: /blog/:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
