baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'LDSoftware'
theme = 'hugo-dark-developer'

[params]
    logo = 'logos/lds_green.png'
    additionalFooter = "I don't use cookies nor track your presence here."
    [params.author]
        name = "Luca Di Stefano"
        email = ""
    [params.social]
        GitHub = "https://github.com/LukeDS-it"

[markup]
    [markup.highlight]
        style = 'dracula'